version: "2"

services:
    www:
        build: ./docker/
        volumes:
            - ./:/docker
            - ./src/html:/var/www/localhost/htdocs
        ports:
            - "8001:80"
        links:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        links:
            - mysql
        ports:
            - 8082:80
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions
